# A comprehensive list of configuration options is available at:
#   https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  TargetRubyVersion: 2.1

Style/NumericLiterals:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/LineLength:
  Max: 100
  Exclude:
    - http-token-auth.gemspec
