# A comprehensive list of configuration options is available at:
#   https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  TargetRubyVersion: 2.1

Style/NumericLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AlignParameters:
  Enabled: true

Style/AlignHash:
  Enabled: true

Metrics/LineLength:
  Max: 100
